import { requestUrl } from "obsidian";

import type { CaptionTrack } from "../types";
import type { PlayerData, RawCaptionTrack } from "./innertube";

export function getCaptionTracks(playerData: PlayerData): CaptionTrack[] {
	const rawTracks =
		playerData.captions?.playerCaptionsTracklistRenderer?.captionTracks ??
		[];
	const tracks: CaptionTrack[] = [];

	rawTracks.forEach((rawTrack) => {
		const track = toCaptionTrack(rawTrack);
		if (track !== null) {
			tracks.push(track);
		}
	});

	return tracks;
}

export async function downloadCaptionXml(
	track: CaptionTrack,
): Promise<string> {
	let response;
	try {
		response = await requestUrl({
			url: getCaptionDownloadUrl(track.baseUrl),
			method: "GET",
			headers: {
				"Accept-Language": "en-US,en;q=0.9",
			},
		});
	} catch {
		throw new Error("Failed to download the selected caption track");
	}

	if (response.text.length === 0) {
		throw new Error("The selected caption track returned an empty response");
	}

	return response.text;
}

function getCaptionDownloadUrl(baseUrl: string): string {
	const url = new URL(baseUrl);
	url.searchParams.set("fmt", "srv3");
	return url.toString();
}

function toCaptionTrack(rawTrack: RawCaptionTrack): CaptionTrack | null {
	if (!rawTrack.baseUrl || !rawTrack.languageCode) {
		return null;
	}

	const isAutoGenerated = rawTrack.kind === "asr";
	const name = getTrackName(rawTrack);

	return {
		baseUrl: rawTrack.baseUrl,
		label: name,
		languageCode: rawTrack.languageCode,
		isAutoGenerated,
	};
}

function getTrackName(rawTrack: RawCaptionTrack): string {
	if (rawTrack.name?.simpleText) {
		return rawTrack.name.simpleText;
	}

	const runs = rawTrack.name?.runs;
	if (runs && runs.length > 0) {
		const text = runs
			.map((run) => run.text ?? "")
			.join("")
			.trim();
		if (text.length > 0) {
			return text;
		}
	}

	return rawTrack.languageCode ?? "Unknown";
}
