import { requestUrl } from "obsidian";

import type { CaptionTrack } from "../types";
import type { PlayerData, RawCaptionTrack } from "./innertube";

export function getCaptionTracks(playerData: PlayerData): CaptionTrack[] {
	const rawTracks =
		playerData.captions?.playerCaptionsTracklistRenderer?.captionTracks ??
		[];
	const tracks: CaptionTrack[] = [];

	rawTracks.forEach((rawTrack) => {
		const track = toCaptionTrack(rawTrack);
		if (track !== null) {
			tracks.push(track);
		}
	});

	return tracks;
}

export async function downloadCaptionXml(
	track: CaptionTrack,
): Promise<string> {
	const response = await requestUrl({
		url: track.baseUrl,
		method: "GET",
		headers: {
			"Accept-Language": "en-US,en;q=0.9",
		},
	});

	if (response.text.length === 0) {
		throw new Error("Received empty caption response");
	}

	return response.text;
}

function toCaptionTrack(rawTrack: RawCaptionTrack): CaptionTrack | null {
	if (!rawTrack.baseUrl || !rawTrack.languageCode) {
		return null;
	}

	const isAutoGenerated = rawTrack.kind === "asr";
	const name = getTrackName(rawTrack);
	const label = isAutoGenerated ? `${name} (auto-generated)` : name;

	return {
		baseUrl: rawTrack.baseUrl,
		label,
		languageCode: rawTrack.languageCode,
		isAutoGenerated,
	};
}

function getTrackName(rawTrack: RawCaptionTrack): string {
	if (rawTrack.name?.simpleText) {
		return rawTrack.name.simpleText;
	}

	const runs = rawTrack.name?.runs;
	if (runs && runs.length > 0) {
		const text = runs
			.map((run) => run.text ?? "")
			.join("")
			.trim();
		if (text.length > 0) {
			return text;
		}
	}

	return rawTrack.languageCode ?? "Unknown";
}
