import { Editor, MarkdownView, Notice, Plugin } from "obsidian";

import { chooseCaptionTrack } from "./modals/caption-track-suggest-modal";
import { promptForYouTubeUrl } from "./modals/url-prompt-modal";
import { formatScript } from "./transcript/format-script";
import { parseCaptionXml } from "./transcript/parse-caption-xml";
import { downloadCaptionXml, getCaptionTracks } from "./youtube/captions";
import { fetchPlayerData } from "./youtube/innertube";
import { extractVideoIdFromUrl } from "./youtube/url";

export default class StrictPlugin extends Plugin {
	onload(): void {
		console.error("[yt-script] plugin loaded");
		this.addCommand({
			id: "import-youtube-script",
			name: "Insert YouTube script",
			editorCallback: (editor) => {
				console.error("[yt-script] command started");
				void this.importYouTubeScript(editor);
			},
		});
	}

	private async importYouTubeScript(editor: Editor): Promise<void> {
		console.error("[yt-script] opening URL prompt");
		const url = await promptForYouTubeUrl(this.app);
		console.error("[yt-script] URL prompt resolved", { url });
		if (url === null) {
			console.error("[yt-script] stopped: URL prompt cancelled");
			return;
		}

		const videoId = extractVideoIdFromUrl(url);
		console.error("[yt-script] extracted video ID", { videoId });
		if (videoId === null) {
			console.error("[yt-script] stopped: invalid YouTube URL", { url });
			new Notice("Enter a valid YouTube URL.");
			return;
		}

		try {
			console.error("[yt-script] fetching player data", { videoId });
			const playerData = await fetchPlayerData(videoId);
			console.error("[yt-script] player data fetched", {
				hasCaptions: Boolean(
					playerData.captions?.playerCaptionsTracklistRenderer
						?.captionTracks,
				),
				playabilityStatus: playerData.playabilityStatus?.status,
				title: playerData.videoDetails?.title,
			});
			const tracks = getCaptionTracks(playerData);
			console.error("[yt-script] caption tracks parsed", {
				count: tracks.length,
				tracks: tracks.map((track) => ({
					label: track.label,
					languageCode: track.languageCode,
					isAutoGenerated: track.isAutoGenerated,
				})),
			});

			if (tracks.length === 0) {
				console.error("[yt-script] stopped: no caption tracks");
				new Notice("No captions are available for this video.");
				return;
			}

			console.error("[yt-script] opening caption track picker");
			const track = await chooseCaptionTrack(this.app, tracks);
			console.error("[yt-script] caption track picker resolved", {
				track,
			});
			if (track === null) {
				console.error("[yt-script] stopped: caption picker cancelled");
				return;
			}

			console.error("[yt-script] downloading caption XML", {
				label: track.label,
				languageCode: track.languageCode,
			});
			const captionXml = await downloadCaptionXml(track);
			console.error("[yt-script] caption XML downloaded", {
				length: captionXml.length,
				preview: captionXml.slice(0, 200),
			});
			const lines = parseCaptionXml(captionXml);
			console.error("[yt-script] caption XML parsed", {
				count: lines.length,
				firstLine: lines[0],
			});
			if (lines.length === 0) {
				console.error("[yt-script] stopped: parsed caption lines empty");
				new Notice("The selected caption track is empty.");
				return;
			}

			const markdown = formatScript(lines);
			console.error("[yt-script] formatted markdown", {
				length: markdown.length,
				preview: markdown.slice(0, 200),
			});
			this.insertScript(editor, markdown);
			console.error("[yt-script] insert completed");
			new Notice("Inserted YouTube script.");
		} catch (error) {
			const message =
				error instanceof Error ? error.message : "Unknown error";
			console.error("[yt-script] failed", error);
			new Notice(`Failed to insert YouTube script: ${message}`);
		}
	}

	private insertScript(editor: Editor, markdown: string): void {
		const activeView = this.app.workspace.getActiveViewOfType(MarkdownView);
		const activeEditor = activeView?.editor ?? editor;
		console.error("[yt-script] inserting into editor", {
			hasActiveView: Boolean(activeView),
			usingActiveEditor: activeEditor !== editor,
			cursor: activeEditor.getCursor(),
			hasSelection: activeEditor.somethingSelected(),
			markdownLength: markdown.length,
		});
		activeEditor.focus();
		activeEditor.replaceSelection(markdown);
	}
}
