export interface PluginSettings {
	outputFolder: string;
}

export interface CaptionTrack {
	baseUrl: string;
	label: string;
	languageCode: string;
	isAutoGenerated: boolean;
}

export interface TranscriptLine {
	text: string;
	offset: number;
	duration: number;
}
